# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='catId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ideas.Category'),
            preserve_default=False,
        ),
    ]
