# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_idea_catid'),
        ('ideas', '0002_idea_owner'),
    ]

    operations = [
    ]
