# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 18:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideas', '0007_auto_20171125_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='last_bid',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='idea',
            name='last_bidder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='potential_buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='idea',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='idea',
            name='starting_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='idea',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
