# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0011_auto_20171130_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='starting_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='last_bid',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='last_bidder',
        ),
    ]
