# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0012_auto_20171130_2007'),
        ('ideas', '0008_auto_20171130_1941'),
    ]

    operations = [
    ]
